# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adc499dc1fedee4ec804f6a14d07ae39d70592fd5c0fc46dc655e9a5fdc4500a8ec542b8a27d91d1371b076c5c51b47089ed899dfecceac590baf4708de1c65f

test:
  secret_key_base: f30d92a35516ff19ec8349cb56f00afaef0e419c4a9903102af33507d604ea1af98d8fb34259c8e11fbe76ebfa217b9d9e5732920352f276ecb2810b2aadee86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
